name: Build EXE
on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install aiofiles==23.2.1 aiohttp==3.11.13 boto3==1.37.4 chainlit==2.2.1 fastapi==0.115.8 itsdangerous==2.2.0 numpy==2.2.2 openai==1.61.1 python-dotenv==1.0.1 python-jose==3.4.0 pyyaml==6.0.2 requests==2.32.3 uvicorn==0.34.0
          
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name keenmind --hidden-import=fastapi --hidden-import=chainlit --hidden-import=uvicorn.logging --hidden-import=uvicorn.loops --hidden-import=uvicorn.loops.auto --hidden-import=uvicorn.protocols --hidden-import=uvicorn.protocols.http --hidden-import=uvicorn.protocols.http.auto --hidden-import=uvicorn.lifespan src/main/main.py
          
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: keenmind-${{ env.VERSION }}
          path: dist/keenmind.exe
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/keenmind.exe
          name: Release ${{ env.VERSION }}